package com.payvault.user.service;

import com.payvault.user.dto.CreateUserRequest;
import com.payvault.user.dto.UpdateUserRequest;
import com.payvault.user.exception.UserAlreadyExistsException;
import com.payvault.user.exception.UserNotFoundException;
import com.payvault.user.model.User;
import com.payvault.user.repository.UserRepository;
import org.springframework.stereotype.Service;

import java.time.Instant;

@Service
public class UserService {

    private final UserRepository userRepository;

    public UserService(UserRepository userRepository) {
        this.userRepository = userRepository;
    }

    public User getByUserId(String userId) {
        return userRepository.findByUserId(userId)
                .orElseThrow(() -> new UserNotFoundException(userId));
    }

    /**
     * Internal creation path, called by auth-service right after a
     * successful registration. userId is generated by auth-service and
     * passed in here rather than generated locally, so both services agree
     * on the same identity for the same person.
     */
    public User create(CreateUserRequest request) {
        if (userRepository.existsByUserId(request.getUserId())) {
            throw new UserAlreadyExistsException("A profile already exists for userId: " + request.getUserId());
        }
        if (userRepository.existsByEmail(request.getEmail())) {
            throw new UserAlreadyExistsException("A profile already exists for email: " + request.getEmail());
        }

        User user = new User(request.getUserId(), request.getName(), request.getEmail(), request.getPhone());
        return userRepository.save(user);
    }

    /**
     * Partial update - only non-null fields on the request are applied.
     * email and status are intentionally not editable here.
     */
    public User update(String userId, UpdateUserRequest request) {
        User user = getByUserId(userId);

        if (request.getName() != null) {
            user.setName(request.getName());
        }
        if (request.getPhone() != null) {
            user.setPhone(request.getPhone());
        }
        if (request.getProfileImage() != null) {
            user.setProfileImage(request.getProfileImage());
        }
        user.setUpdatedAt(Instant.now());

        return userRepository.save(user);
    }
}
